# Generated by Django 3.1.7 on 2021-03-31 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0002_auto_20210331_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_id',
        ),
    ]
