# Generated by Django 3.1.7 on 2021-03-31 08:03

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0004_video_uploaded'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='video',
            managers=[
                ('playlist', django.db.models.manager.Manager()),
            ],
        ),
    ]
